### ISSUE TITLE
Triplets dataset link is incorrect

### ISSUE THREAD

**Issue by zuoxiang95** [rxtan2/Learning-Similarity-Conditions#1]
Hello, thanks for your excellent work. I try to get your train dataset but found the triplets dataset link is incorrect.

**Comment by zbr17** [comment]
Hello, I met the same problem as you. Can I ask for your solution if you fix this?

**Comment by rxtan2** [comment]
Hi, thank you for your interest in our work.  I will update the readme asap and let you guys know.

**Comment by rxtan2** [comment]
I have updated the README with more detailed instructions. Please let me know if you still have any problems running the code. Apologies for the delay!

**Comment by zuoxiang95** [comment]
@zbr17 I guess the true dataset URL is: https://vision.cornell.edu/se3/wp-content/uploads/2019/05/csn_zappos_triplets.zip  from [here](https://github.com/andreasveit/conditional-similarity-networks/blob/9233b5d36fb1dd977a2b554f4baf1285bb344618/get_data.py#L21)

**Comment by zbr17** [comment]
Thank you very much. @zuoxiang95 @rxtan2

**Comment by rxtan2** [comment]
Hi Zuoxiang, 

Do you still have problems setting up or running the code?  Otherwise, I will close this issue.
