### ISSUE TITLE
Not all the triplets are used?

### ISSUE THREAD

**Issue by Maryeon** [rxtan2/Learning-Similarity-Conditions#10]
Hi, I was wondering why just 200k triplets are used to train the network. Will the full use of Zappos training triplets produce better performance or induce overfitting? Thanks a lot!

**Comment by rxtan2** [comment]
Hi, if I remember correctly, we only used 200k triplets for training to maintain fair comparisons with some prior work.

**Comment by Maryeon** [comment]
Thank you! That really helps!
