### ISSUE TITLE
Repository structure of Triplets Datasets

### ISSUE THREAD

**Issue by zbr17** [rxtan2/Learning-Similarity-Conditions#2]
Hello, thanks for your excellent work. I would appreciate it if you could upload more detailed information on the repository structure, especially for the Triplets Datasets?

**Comment by rxtan2** [comment]
Hi, thank you for your interest in our work.  I have updated the README with more detailed instructions.  Please let me know if you still have any problems running the code. Apologies for the delay!

**Comment by zbr17** [comment]
Thanks a lot.
