### ISSUE TITLE
Input parameter c for csn network during inference

### ISSUE THREAD

**Issue by davidsonic** [rxtan2/Learning-Similarity-Conditions#5]
Hi, thank you for code release. A question about condition c as input for csn forward function during inference. In type-aware paper, they got c by extracting from predefined typespace determined by img1 type and img2 type. Here in training, it seems that an averaged embedding/score from all possible conditions is used. Are we expected to do the same during inference?

**Comment by rxtan2** [comment]
Hi, I am not quite getting your question. Here, we are using all possible c which, in this case, is 4.  The difference is that we are weighting the contribution of each c.

**Comment by davidsonic** [comment]
Thanks for your response. I understand that weights for M conditional branches are used. However, in order to generate these weights, the concept_branch takes in a concatenation of 3 items (64x3) in this case during training. During testing, such as fitb prediction, we'll take two items each time to compute their distances, in this case, how am I supposed to provide this 64x3 feature for generating weights?

**Comment by rxtan2** [comment]
Hi, due to this limitation, the concept_branch only takes in a concatenation of 2 items (64x2) during both training and testing on the Polyvore dataset.

**Comment by davidsonic** [comment]
If this is the case, can you release the complete code such as fitb part?

**Comment by rxtan2** [comment]
Sure, give me some time to set it up.  Thanks for your patience.
