### ISSUE TITLE
How to reproduce results of polyvore performance reported in the paper with this code?

### ISSUE THREAD

**Issue by hejia-zhang** [rxtan2/Learning-Similarity-Conditions#6]
The released code gives me around 86% acc in terms of distance comparison in a triplet, however, I can't tell if this is sufficient to reproduce fitb acc claimed in the paper.

**Comment by rxtan2** [comment]
Hi, do you mean you got 86% for the final accuracy on the Zappos50k dataset?  That is a few percents lower than our obtained results.  One important thing to check is if you are using the specified version of Pytorch.  We have observed lower performance after converting the model to newer versions of Pytorch.

**Comment by DrFV** [comment]
I think he means that he got 0.86 for the Compat AUC on the polyvore outfits dataset. I also got similar performance, which is much lower than the performance reported in the paper.
