### ISSUE TITLE
The condition used in Polyvore dataset

### ISSUE THREAD

**Issue by zuoxiang95** [rxtan2/Learning-Similarity-Conditions#7]
hello, @rxtan2 
In your paper, I found you use 5 conditions to get the best result in the Polyvore dataset. Can you explain what conditions you used? Because I see in UT-Zappos50K, it has gender, class, closure and heel condition.

**Comment by rxtan2** [comment]
Hi Zuo Xiang, the 5 condition masks do not correspond to specific masks. Instead, they are used to approximate the relevant semantic subspace for pairwise comparison.  Our model is weakly-supervised and therefore, do not rely on explicitly-defined labels.

**Comment by zuoxiang95** [comment]
@rxtan2 Thanks for your kind reply, I probably understand what you mean. But I still don't know how to make the triplets in the Polyvore dataset. I want to train your model in the Polyvore dataset. Can you give me any advice? Thanks again : )

**Comment by zuoxiang95** [comment]
hello @rxtan2 , I recently run your model with my own dataset and the model performed well on the test dataset. When I wrote an inference, I found the model need to feed three images to get the attention weights. But when the model predicts outfit compatibility, there is not a triplet.

**Comment by Charlie1994** [comment]
> hello @rxtan2 , I recently run your model with my own dataset and the model performed well on the test dataset. When I wrote an inference, I found the model need to feed three images to get the attention weights. But when the model predicts outfit compatibility, there is not a triplet.

I think you can treat the averaged compatibility score of each pair of fashion items within an outfit as the final prediction score for an outfit. The implementation of their previous work, CSN [1] is quite similar to this work, in terms of compatibility score calculation.

[1] Learning type-aware embeddings for fashion compatibility, ECCV 2018

**Comment by zuoxiang95** [comment]
@Charlie1994 I had seen their previous work, and I combine these two networks. It seems nice~

**Comment by rxtan2** [comment]
@zuoxiang95 Hi Zuo Xiang, apologies for not  checking this thread. What you can do is create attention vectors for each pair of samples. In addition, you can try out what @Charlie1994 has suggested. Btw, if it's not too much problem, do you mind emailing me if you need more clarifications. For some reason, I am not receiving email notifications for github activity.
